[workspace]
resolver = "3"
members = [
  "crates/*",
	"server/*",
	"client/*",
	"tests",
]
default-membres = [ "server/*" , "client/*" ]

[workspace.dependencies]
protocol = { path = "crates/protocol" }
